/*
 * test_roles.c — role derivation and the role audit.
 *
 * One test per derivation rule, each against a real fixture tree; the
 * precedence ladder; the A5 fail-closed default; and the A7 audit, which
 * must REPORT a contradiction and leave the role untouched.
 *
 * The two real-registry tests (vendored, upstream set) run against THIS
 * repository's own registry files, because A2/A4's whole claim is "derive
 * from the registry that already exists" — a test that only ever reads a
 * fixture invented here would never notice the real format drifting.
 */
#include "test_framework.h"
#include "test_helpers.h"

#include "discover/role.h"

#include <stdio.h>
#include <string.h>

/* 64 hex chars — the shape scripts/vendored-checksums.txt actually holds.
 * The VALUE is irrelevant to role derivation; only coverage is read. */
#define FAKE_SHA "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

static const char MARKED_HEAD[] = "/* Code generated by fixture-gen. DO NOT EDIT. */\nint x;\n";
static const char PLAIN_HEAD[] = "/* hand-written */\nint y;\n";

/* Write a fixture registry repo declaring example upstreams in the two real
 * formats (provenance audit LIBS/FORKS lines, grammar manifest table row). */
static int write_registry_fixture(const char *reg_root) {
    int rc = th_write_file(TH_PATH(reg_root, "scripts/audit-license-provenance.py"),
                           "LIBS = {\n"
                           "    \"vendored/example-lib\": (\"Example-Org/Example-Lib\", None),\n"
                           "}\n"
                           "FORKS = {\n"
                           "    \"thing\": \"other-org/thing-fork\",\n"
                           "}\n");
    rc |= th_write_file(TH_PATH(reg_root, "internal/hyp/vendored/grammars/MANIFEST.md"),
                        "| grammar | abi | upstream | pinned | verdict | ok |\n"
                        "|---|---|---|---|---|---|\n"
                        "| ada | 14 | briot/tree-sitter-ada | `abc123` | VERIFIED-BOTH | ok |\n");
    return rc;
}

/* Point a fixture repo's origin at url via a plain .git/config. */
static int write_repo_with_origin(const char *repo_root, const char *url) {
    char config[512];
    (void)snprintf(config, sizeof config,
                   "[core]\n\trepositoryformatversion = 0\n"
                   "[remote \"origin\"]\n\turl = %s\n\tfetch = +refs/heads/*:refs/remotes/origin/*\n",
                   url);
    return th_write_file(TH_PATH(repo_root, ".git/config"), config);
}

/* ════════════════════════════════════════════════════════════════════
 * A2 — vendored, derived from the checksum registry
 * ════════════════════════════════════════════════════════════════════ */

TEST(roles_vendored_derived_from_fixture_registry) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a2");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    ASSERT_EQ(th_write_file(TH_PATH(base, "host/scripts/vendored-checksums.txt"),
                            FAKE_SHA "  third_party/libfoo/foo.c\n" FAKE_SHA
                                     "  third_party/libfoo/LICENSE\n"),
              0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/third_party/libfoo/foo.c"), "int foo;\n"), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/third_party/other/bar.c"), "int bar;\n"), 0);

    char ev[HYP_ROLE_EVIDENCE_MAX + 1];
    ev[0] = '\0';
    ASSERT_TRUE(hyp_role_is_vendored(TH_PATH(base, "host/third_party/libfoo"), ev, sizeof ev));
    /* The evidence names the registry, not a guess. */
    ASSERT_NOT_NULL(strstr(ev, "vendored-checksums.txt"));

    /* An unregistered sibling is NOT vendored — coverage comes from the
     * registry's entries, never from the directory's neighbourhood. */
    ASSERT_FALSE(hyp_role_is_vendored(TH_PATH(base, "host/third_party/other"), NULL, 0));
    /* Nor is the repository that CARRIES the manifest. */
    ASSERT_FALSE(hyp_role_is_vendored(TH_PATH(base, "host"), NULL, 0));

    hyp_role_result_t r;
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "host/third_party/libfoo"), NULL, &r));
    ASSERT_EQ(r.role, HYP_ROLE_VENDORED);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DERIVED_VENDORED_REGISTRY);

    th_cleanup(base);
    PASS();
}

TEST(roles_vendored_coverage_respects_path_boundaries) {
    /* "third_party/libfoobar/x.c" must not cover "third_party/libfoo" — a
     * prefix match without a component boundary is a different tree. */
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a2b");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    ASSERT_EQ(th_write_file(TH_PATH(base, "host/scripts/vendored-checksums.txt"),
                            FAKE_SHA "  third_party/libfoobar/x.c\n"),
              0);
    ASSERT_EQ(th_mkdir_p(TH_PATH(base, "host/third_party/libfoo")), 0);
    ASSERT_FALSE(hyp_role_is_vendored(TH_PATH(base, "host/third_party/libfoo"), NULL, 0));

    th_cleanup(base);
    PASS();
}

TEST(roles_vendored_reads_the_registry_that_already_exists) {
    /* THIS repository's registry, in its real format. If these fail, either
     * the test is not running from the repo root (a harness bug) or the
     * registry format changed and role derivation silently stopped seeing
     * vendored code — exactly the drift this test exists to catch. */
    if (!hyp_file_exists("scripts/vendored-checksums.txt"))
        FAIL("must run from the repository root");

    char ev[HYP_ROLE_EVIDENCE_MAX + 1];
    ev[0] = '\0';
    ASSERT_TRUE(hyp_role_is_vendored("vendored/llama.cpp", ev, sizeof ev));
    ASSERT_NOT_NULL(strstr(ev, "vendored/llama.cpp"));
    ASSERT_TRUE(hyp_role_is_vendored("internal/hyp/vendored/lz4", NULL, 0));
    ASSERT_FALSE(hyp_role_is_vendored("src", NULL, 0));
    PASS();
}

/* ════════════════════════════════════════════════════════════════════
 * A3 — generated, from gitignore semantics and DO-NOT-EDIT headers
 * ════════════════════════════════════════════════════════════════════ */

TEST(roles_generated_derived_from_gitignore) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a3");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    ASSERT_EQ(th_mkdir_p(TH_PATH(base, "repo/.git")), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "repo/.gitignore"), "build/\n"), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "repo/build/out/gen.o"), "obj\n"), 0);

    char ev[HYP_ROLE_EVIDENCE_MAX + 1];
    ev[0] = '\0';
    ASSERT_TRUE(hyp_role_is_gitignored(TH_PATH(base, "repo/build/out"), ev, sizeof ev));
    ASSERT_NOT_NULL(strstr(ev, ".gitignore"));
    /* A tracked sibling is not gitignored. */
    ASSERT_EQ(th_mkdir_p(TH_PATH(base, "repo/src")), 0);
    ASSERT_FALSE(hyp_role_is_gitignored(TH_PATH(base, "repo/src"), NULL, 0));
    /* No enclosing repository at all → no gitignore verdict either way. */
    ASSERT_EQ(th_mkdir_p(TH_PATH(base, "loose/build")), 0);
    ASSERT_FALSE(hyp_role_is_gitignored(TH_PATH(base, "loose/build"), NULL, 0));

    hyp_role_result_t r;
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "repo/build/out"), NULL, &r));
    ASSERT_EQ(r.role, HYP_ROLE_GENERATED);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DERIVED_GITIGNORE);

    th_cleanup(base);
    PASS();
}

TEST(roles_generated_derived_from_gitignore_on_this_repository) {
    /* Two-ends check against the real tree: this repo's own build directory
     * is gitignored, so its role derives generated with no fixture. */
    if (!hyp_file_exists(".gitignore")) FAIL("must run from the repository root");
    if (!hyp_is_dir("build")) FAIL("expected a build/ directory (tests run after a build)");

    hyp_role_result_t r;
    ASSERT_TRUE(hyp_role_derive("build", NULL, &r));
    ASSERT_EQ(r.role, HYP_ROLE_GENERATED);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DERIVED_GITIGNORE);
    PASS();
}

TEST(roles_generated_derived_from_do_not_edit_headers) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a3b");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    ASSERT_EQ(th_write_file(TH_PATH(base, "gen/a.c"), MARKED_HEAD), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "gen/b.c"), MARKED_HEAD), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "gen/sub/c.c"), MARKED_HEAD), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "gen/README"), PLAIN_HEAD), 0);

    hyp_role_scan_t scan;
    ASSERT_TRUE(hyp_role_scan_do_not_edit(TH_PATH(base, "gen"), &scan));
    ASSERT_EQ(scan.sampled, 4);
    ASSERT_EQ(scan.marked, 3);
    ASSERT_TRUE(hyp_role_scan_majority(&scan));

    hyp_role_result_t r;
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "gen"), NULL, &r));
    ASSERT_EQ(r.role, HYP_ROLE_GENERATED);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DERIVED_DO_NOT_EDIT);

    /* A half-and-half tree is NOT generated — the rule needs a strict
     * majority, not a whiff. */
    ASSERT_EQ(th_write_file(TH_PATH(base, "half/a.c"), MARKED_HEAD), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "half/b.c"), PLAIN_HEAD), 0);
    ASSERT_TRUE(hyp_role_scan_do_not_edit(TH_PATH(base, "half"), &scan));
    ASSERT_FALSE(hyp_role_scan_majority(&scan));

    th_cleanup(base);
    PASS();
}

TEST(roles_do_not_edit_scan_is_bounded_and_skips_binaries) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a3c");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    /* A binary head (NUL byte) is outside the sample, not counted. */
    char rel[64];
    ASSERT_EQ(th_write_file(TH_PATH(base, "bin/t.c"), MARKED_HEAD), 0);
    {
        FILE *f = hyp_fopen(TH_PATH(base, "bin/blob.bin"), "wb");
        if (!f) FAIL("cannot write binary fixture");
        fputc('\0', f);
        fputs("DO NOT EDIT", f);
        fclose(f);
    }
    hyp_role_scan_t scan;
    ASSERT_TRUE(hyp_role_scan_do_not_edit(TH_PATH(base, "bin"), &scan));
    ASSERT_EQ(scan.sampled, 1);
    ASSERT_EQ(scan.marked, 1);

    /* The sample is bounded: more files than the cap, still cap samples. */
    for (int i = 0; i < HYP_ROLE_SCAN_MAX_FILES + 6; i++) {
        (void)snprintf(rel, sizeof rel, "many/f%03d.c", i);
        ASSERT_EQ(th_write_file(TH_PATH(base, rel), MARKED_HEAD), 0);
    }
    ASSERT_TRUE(hyp_role_scan_do_not_edit(TH_PATH(base, "many"), &scan));
    ASSERT_EQ(scan.sampled, HYP_ROLE_SCAN_MAX_FILES);
    ASSERT_EQ(scan.marked, HYP_ROLE_SCAN_MAX_FILES);

    th_cleanup(base);
    PASS();
}

/* ════════════════════════════════════════════════════════════════════
 * A4 — upstream, from the git remote
 * ════════════════════════════════════════════════════════════════════ */

TEST(roles_remote_coordinate_normalizes_the_real_url_forms) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a4");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    char coord[HYP_ROLE_COORD_MAX + 1];

    ASSERT_EQ(write_repo_with_origin(TH_PATH(base, "https"),
                                     "https://github.com/Example-Org/Example-Lib.git"),
              0);
    ASSERT_TRUE(hyp_role_remote_coordinate(TH_PATH(base, "https"), coord, sizeof coord));
    ASSERT_STR_EQ(coord, "example-org/example-lib");

    ASSERT_EQ(write_repo_with_origin(TH_PATH(base, "scp"), "git@github.com:Example-Org/Example-Lib.git"),
              0);
    ASSERT_TRUE(hyp_role_remote_coordinate(TH_PATH(base, "scp"), coord, sizeof coord));
    ASSERT_STR_EQ(coord, "example-org/example-lib");

    ASSERT_EQ(write_repo_with_origin(TH_PATH(base, "ssh"), "ssh://git@example.com:2222/Example-Org/Example-Lib"),
              0);
    ASSERT_TRUE(hyp_role_remote_coordinate(TH_PATH(base, "ssh"), coord, sizeof coord));
    ASSERT_STR_EQ(coord, "example-org/example-lib");

    /* A filesystem remote has no owner/name shape: fail closed, no signal. */
    ASSERT_EQ(write_repo_with_origin(TH_PATH(base, "fs"), "/srv/git/example.git"), 0);
    ASSERT_FALSE(hyp_role_remote_coordinate(TH_PATH(base, "fs"), coord, sizeof coord));

    /* No .git at all: no signal. */
    ASSERT_EQ(th_mkdir_p(TH_PATH(base, "bare")), 0);
    ASSERT_FALSE(hyp_role_remote_coordinate(TH_PATH(base, "bare"), coord, sizeof coord));

    th_cleanup(base);
    PASS();
}

TEST(roles_remote_coordinate_follows_worktree_indirection) {
    /* A worktree's .git is a FILE naming a gitdir, whose commondir names the
     * shared .git — this very checkout is one, so the mechanism is not
     * optional. Files only, no subprocess. */
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a4b");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    ASSERT_EQ(write_repo_with_origin(TH_PATH(base, "main"),
                                     "https://github.com/Example-Org/Example-Lib.git"),
              0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "main/.git/worktrees/wt/commondir"), "../..\n"), 0);
    ASSERT_EQ(th_mkdir_p(TH_PATH(base, "wtco")), 0);
    {
        char gitfile[512];
        (void)snprintf(gitfile, sizeof gitfile, "gitdir: %s/main/.git/worktrees/wt\n", base);
        ASSERT_EQ(th_write_file(TH_PATH(base, "wtco/.git"), gitfile), 0);
    }

    char coord[HYP_ROLE_COORD_MAX + 1];
    ASSERT_TRUE(hyp_role_remote_coordinate(TH_PATH(base, "wtco"), coord, sizeof coord));
    ASSERT_STR_EQ(coord, "example-org/example-lib");

    th_cleanup(base);
    PASS();
}

TEST(roles_upstream_derived_from_remote_and_registry) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a4c");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    ASSERT_EQ(write_registry_fixture(TH_PATH(base, "reg")), 0);
    hyp_role_upstreams_t set;
    hyp_role_upstreams_init(&set);
    ASSERT_TRUE(hyp_role_upstreams_load(&set, TH_PATH(base, "reg")));
    ASSERT_EQ(set.count, 3); /* LIBS + FORKS + grammar manifest rows */

    ASSERT_EQ(write_repo_with_origin(TH_PATH(base, "clone"),
                                     "https://github.com/Example-Org/Example-Lib.git"),
              0);

    hyp_role_ctx_t ctx = {0};
    ctx.known_upstreams = &set;

    char ev[HYP_ROLE_EVIDENCE_MAX + 1];
    ev[0] = '\0';
    ASSERT_TRUE(hyp_role_is_upstream(TH_PATH(base, "clone"), &ctx, ev, sizeof ev));
    ASSERT_NOT_NULL(strstr(ev, "example-org/example-lib"));

    hyp_role_result_t r;
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "clone"), &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_UPSTREAM);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DERIVED_REMOTE);

    /* THE OTHER HALF OF THE RULE: a checkout whose origin IS the workspace's
     * own origin is another copy of this project, never its upstream. */
    ctx.workspace_origin = "example-org/example-lib";
    ASSERT_FALSE(hyp_role_is_upstream(TH_PATH(base, "clone"), &ctx, NULL, 0));
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "clone"), &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_REFERENCE);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DEFAULT_REFERENCE);

    /* A remote in NO registry is not upstream of anything here. */
    ctx.workspace_origin = NULL;
    ASSERT_EQ(write_repo_with_origin(TH_PATH(base, "rando"),
                                     "https://github.com/somebody/inspiration.git"),
              0);
    ASSERT_FALSE(hyp_role_is_upstream(TH_PATH(base, "rando"), &ctx, NULL, 0));

    hyp_role_upstreams_free(&set);
    th_cleanup(base);
    PASS();
}

TEST(roles_upstreams_load_reads_the_existing_registries) {
    /* The real files, the real formats: the provenance audit's LIBS table
     * (ggml-org/llama.cpp is the unit's own named example), its FORKS table,
     * and the grammar manifest's verified-upstream rows. */
    if (!hyp_file_exists("scripts/audit-license-provenance.py"))
        FAIL("must run from the repository root");

    hyp_role_upstreams_t set;
    hyp_role_upstreams_init(&set);
    ASSERT_TRUE(hyp_role_upstreams_load(&set, "."));
    ASSERT_GT(set.count, 0);

    bool llama = false;
    bool ada = false;
    bool cfml = false;
    for (size_t i = 0; i < set.count; i++) {
        if (strcmp(set.entries[i].coord, "ggml-org/llama.cpp") == 0) llama = true;
        if (strcmp(set.entries[i].coord, "briot/tree-sitter-ada") == 0) ada = true;
        if (strcmp(set.entries[i].coord, "cfmleditor/tree-sitter-cfml") == 0) cfml = true;
    }
    ASSERT_TRUE(llama);
    ASSERT_TRUE(ada);
    ASSERT_TRUE(cfml);

    /* Every loaded entry is a well-formed coordinate — prose strings that
     * happen to follow a colon in the Python source must not leak in. */
    for (size_t i = 0; i < set.count; i++) {
        ASSERT_NOT_NULL(strchr(set.entries[i].coord, '/'));
        ASSERT_NULL(strchr(set.entries[i].coord, ' '));
        ASSERT_NULL(strchr(set.entries[i].coord, '('));
    }

    hyp_role_upstreams_free(&set);
    PASS();
}

/* ════════════════════════════════════════════════════════════════════
 * A5 — unknown defaults to reference, ALWAYS
 * ════════════════════════════════════════════════════════════════════ */

TEST(roles_no_signals_at_all_defaults_to_reference) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a5");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    ASSERT_EQ(th_mkdir_p(TH_PATH(base, "plainrepo/src")), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "plainrepo/src/main.c"), PLAIN_HEAD), 0);

    hyp_role_result_t r;
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "plainrepo"), NULL, &r));
    ASSERT_EQ(r.role, HYP_ROLE_REFERENCE);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DEFAULT_REFERENCE);

    /* An unreadable tree is also "no signals": reference, not a guess. */
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "does-not-exist"), NULL, &r));
    ASSERT_EQ(r.role, HYP_ROLE_REFERENCE);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DEFAULT_REFERENCE);

    th_cleanup(base);
    PASS();
}

TEST(roles_unrecognised_declaration_fails_closed_to_reference) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a5b");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    /* Even WITH derivable evidence in the tree: an unknown declared role is
     * reference, ALWAYS — a declaration this module cannot read must not be
     * reinterpreted into something else, however plausible. */
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/scripts/vendored-checksums.txt"),
                            FAKE_SHA "  lib/x.c\n"),
              0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/lib/x.c"), "int x;\n"), 0);

    hyp_role_ctx_t ctx = {0};
    ctx.declared = "maintainer"; /* not a role */
    hyp_role_result_t r;
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "host/lib"), &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_REFERENCE);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DEFAULT_REFERENCE);
    ASSERT_NOT_NULL(strstr(r.evidence, "maintainer"));

    th_cleanup(base);
    PASS();
}

/* ════════════════════════════════════════════════════════════════════
 * Precedence — declared > vendored > gitignore > do-not-edit > remote
 *              > default, one ladder, every rung real
 * ════════════════════════════════════════════════════════════════════ */

TEST(roles_precedence_ladder) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_prec");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    /* One candidate carrying EVERY signal at once. */
    ASSERT_EQ(th_mkdir_p(TH_PATH(base, "host/.git")), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/.gitignore"), "vendor_gen/\n"), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/scripts/vendored-checksums.txt"),
                            FAKE_SHA "  vendor_gen/lib/gen1.h\n"),
              0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/vendor_gen/lib/gen1.h"), MARKED_HEAD), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/vendor_gen/lib/gen2.h"), MARKED_HEAD), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/vendor_gen/lib/gen3.h"), MARKED_HEAD), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/vendor_gen/lib/notes.txt"), PLAIN_HEAD), 0);
    ASSERT_EQ(write_repo_with_origin(TH_PATH(base, "host/vendor_gen/lib"),
                                     "https://github.com/Example-Org/Example-Lib.git"),
              0);

    ASSERT_EQ(write_registry_fixture(TH_PATH(base, "reg")), 0);
    hyp_role_upstreams_t set;
    hyp_role_upstreams_init(&set);
    ASSERT_TRUE(hyp_role_upstreams_load(&set, TH_PATH(base, "reg")));

    hyp_role_ctx_t ctx = {0};
    ctx.known_upstreams = &set;
    hyp_role_result_t r;
    char cand[512];
    (void)snprintf(cand, sizeof cand, "%s/host/vendor_gen/lib", base);

    /* 1. Declaration outranks every derivation. */
    ctx.declared = "upstream";
    ASSERT_TRUE(hyp_role_derive(cand, &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_UPSTREAM);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DECLARED_TOML);

    /* 2. No declaration: the checksum registry wins. */
    ctx.declared = NULL;
    ASSERT_TRUE(hyp_role_derive(cand, &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_VENDORED);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DERIVED_VENDORED_REGISTRY);

    /* 3. Registry gone: gitignore speaks next. */
    ASSERT_EQ(th_rmtree(TH_PATH(base, "host/scripts")), 0);
    ASSERT_TRUE(hyp_role_derive(cand, &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_GENERATED);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DERIVED_GITIGNORE);

    /* 4. Gitignore gone: the DO-NOT-EDIT majority speaks. */
    ASSERT_EQ(th_rmtree(TH_PATH(base, "host/.gitignore")), 0);
    ASSERT_TRUE(hyp_role_derive(cand, &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_GENERATED);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DERIVED_DO_NOT_EDIT);

    /* 5. Markers gone: the remote speaks. */
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/vendor_gen/lib/gen1.h"), PLAIN_HEAD), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/vendor_gen/lib/gen2.h"), PLAIN_HEAD), 0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/vendor_gen/lib/gen3.h"), PLAIN_HEAD), 0);
    ASSERT_TRUE(hyp_role_derive(cand, &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_UPSTREAM);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DERIVED_REMOTE);

    /* 6. No remote context left: the fail-closed floor. */
    ctx.known_upstreams = NULL;
    ASSERT_TRUE(hyp_role_derive(cand, &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_REFERENCE);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DEFAULT_REFERENCE);

    hyp_role_upstreams_free(&set);
    th_cleanup(base);
    PASS();
}

/* ════════════════════════════════════════════════════════════════════
 * A7 — the audit reports; it NEVER reassigns
 * ════════════════════════════════════════════════════════════════════ */

TEST(roles_audit_reports_member_do_not_edit_contradiction) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a7");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    /* Ten files, nine generated — the unit's own fixture: a repo tagged
     * member whose files are overwhelmingly DO NOT EDIT. */
    char rel[64];
    for (int i = 0; i < 9; i++) {
        (void)snprintf(rel, sizeof rel, "tagged/gen%d.c", i);
        ASSERT_EQ(th_write_file(TH_PATH(base, rel), MARKED_HEAD), 0);
    }
    ASSERT_EQ(th_write_file(TH_PATH(base, "tagged/main.c"), PLAIN_HEAD), 0);

    hyp_role_ctx_t ctx = {0};
    ctx.declared = "member";
    hyp_role_result_t r;
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "tagged"), &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_MEMBER);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DECLARED_TOML);

    hyp_role_result_t before = r;
    hyp_role_contradiction_t contra[4];
    size_t n = hyp_role_audit(TH_PATH(base, "tagged"), &r, &ctx, contra, 4);
    ASSERT_EQ(n, 1);
    ASSERT_EQ(contra[0].kind, HYP_ROLE_CONTRA_MEMBER_DO_NOT_EDIT);
    ASSERT_NOT_NULL(strstr(contra[0].evidence, "9 of 10"));

    /* REPORT, not absorb: the resolved role is unchanged after the audit —
     * role, source and evidence all. This assertion IS the A7 contract. */
    ASSERT_EQ(r.role, HYP_ROLE_MEMBER);
    ASSERT_EQ(r.source, HYP_ROLE_SRC_DECLARED_TOML);
    ASSERT_EQ(before.role, r.role);
    ASSERT_EQ(before.source, r.source);
    ASSERT_STR_EQ(before.evidence, r.evidence);

    th_cleanup(base);
    PASS();
}

TEST(roles_audit_reports_member_vendored_and_upstream_contradictions) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a7b");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    /* member, but registered vendored AND cloned from a known upstream AND
     * overwhelmingly DO-NOT-EDIT: three contradictions. */
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/scripts/vendored-checksums.txt"),
                            FAKE_SHA "  third_party/libfoo/gen.c\n"),
              0);
    ASSERT_EQ(th_write_file(TH_PATH(base, "host/third_party/libfoo/gen.c"), MARKED_HEAD), 0);
    ASSERT_EQ(write_repo_with_origin(TH_PATH(base, "host/third_party/libfoo"),
                                     "https://github.com/Example-Org/Example-Lib.git"),
              0);
    ASSERT_EQ(write_registry_fixture(TH_PATH(base, "reg")), 0);

    hyp_role_upstreams_t set;
    hyp_role_upstreams_init(&set);
    ASSERT_TRUE(hyp_role_upstreams_load(&set, TH_PATH(base, "reg")));

    hyp_role_ctx_t ctx = {0};
    ctx.declared = "member";
    ctx.known_upstreams = &set;
    hyp_role_result_t r;
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "host/third_party/libfoo"), &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_MEMBER);

    /* cap 1 < findings 3: the return value is the TRUE count — a floor is
     * only a floor when nothing above it is silently dropped. */
    hyp_role_contradiction_t one[1];
    size_t n = hyp_role_audit(TH_PATH(base, "host/third_party/libfoo"), &r, &ctx, one, 1);
    ASSERT_EQ(n, 3);
    ASSERT_EQ(one[0].kind, HYP_ROLE_CONTRA_MEMBER_VENDORED);
    ASSERT_EQ(r.role, HYP_ROLE_MEMBER); /* still member; still only reported */

    hyp_role_upstreams_free(&set);
    th_cleanup(base);
    PASS();
}

TEST(roles_audit_is_asymmetric_and_silent_when_consistent) {
    char base[256];
    char *tmp = th_mktempdir("hyp_roles_a7c");
    if (!tmp) FAIL("th_mktempdir returned NULL");
    snprintf(base, sizeof base, "%s", tmp);

    /* A consistent member: nothing to report. */
    ASSERT_EQ(th_write_file(TH_PATH(base, "mine/src/main.c"), PLAIN_HEAD), 0);
    hyp_role_ctx_t ctx = {0};
    ctx.declared = "member";
    hyp_role_result_t r;
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "mine"), &ctx, &r));
    hyp_role_contradiction_t contra[4];
    ASSERT_EQ(hyp_role_audit(TH_PATH(base, "mine"), &r, &ctx, contra, 4), 0);

    /* A read-only role over a generated tree is NOT audited — vendored code
     * full of DO-NOT-EDIT headers is the world working as designed, and a
     * wrong read-only tag is recoverable, not hazardous. */
    ASSERT_EQ(th_write_file(TH_PATH(base, "gen/a.c"), MARKED_HEAD), 0);
    ctx.declared = "vendored";
    ASSERT_TRUE(hyp_role_derive(TH_PATH(base, "gen"), &ctx, &r));
    ASSERT_EQ(r.role, HYP_ROLE_VENDORED);
    ASSERT_EQ(hyp_role_audit(TH_PATH(base, "gen"), &r, &ctx, contra, 4), 0);

    th_cleanup(base);
    PASS();
}

/* ── Wire names — both directions, so the resolver and the TOML agree ── */

TEST(roles_names_round_trip) {
    static const hyp_role_t all[] = {HYP_ROLE_MEMBER, HYP_ROLE_VENDORED, HYP_ROLE_GENERATED,
                                     HYP_ROLE_UPSTREAM, HYP_ROLE_REFERENCE};
    for (size_t i = 0; i < sizeof all / sizeof all[0]; i++) {
        hyp_role_t parsed;
        ASSERT_TRUE(hyp_role_parse(hyp_role_name(all[i]), &parsed));
        ASSERT_EQ(parsed, all[i]);
    }
    hyp_role_t out;
    ASSERT_FALSE(hyp_role_parse("Member", &out)); /* strict: one spelling */
    ASSERT_FALSE(hyp_role_parse("", &out));
    ASSERT_FALSE(hyp_role_parse(NULL, &out));

    /* The six disclosure tokens, verbatim from the plan. */
    ASSERT_STR_EQ(hyp_role_source_name(HYP_ROLE_SRC_DECLARED_TOML), "declared-toml");
    ASSERT_STR_EQ(hyp_role_source_name(HYP_ROLE_SRC_DERIVED_VENDORED_REGISTRY),
                  "derived-vendored-registry");
    ASSERT_STR_EQ(hyp_role_source_name(HYP_ROLE_SRC_DERIVED_GITIGNORE), "derived-gitignore");
    ASSERT_STR_EQ(hyp_role_source_name(HYP_ROLE_SRC_DERIVED_DO_NOT_EDIT), "derived-do-not-edit");
    ASSERT_STR_EQ(hyp_role_source_name(HYP_ROLE_SRC_DERIVED_REMOTE), "derived-remote");
    ASSERT_STR_EQ(hyp_role_source_name(HYP_ROLE_SRC_DEFAULT_REFERENCE), "default-reference");
    PASS();
}

/* ── Suite ───────────────────────────────────────────────────────── */

SUITE(roles) {
    /* A2 — vendored from the existing registry */
    RUN_TEST(roles_vendored_derived_from_fixture_registry);
    RUN_TEST(roles_vendored_coverage_respects_path_boundaries);
    RUN_TEST(roles_vendored_reads_the_registry_that_already_exists);

    /* A3 — generated */
    RUN_TEST(roles_generated_derived_from_gitignore);
    RUN_TEST(roles_generated_derived_from_gitignore_on_this_repository);
    RUN_TEST(roles_generated_derived_from_do_not_edit_headers);
    RUN_TEST(roles_do_not_edit_scan_is_bounded_and_skips_binaries);

    /* A4 — upstream from the remote */
    RUN_TEST(roles_remote_coordinate_normalizes_the_real_url_forms);
    RUN_TEST(roles_remote_coordinate_follows_worktree_indirection);
    RUN_TEST(roles_upstream_derived_from_remote_and_registry);
    RUN_TEST(roles_upstreams_load_reads_the_existing_registries);

    /* A5 — the fail-closed default */
    RUN_TEST(roles_no_signals_at_all_defaults_to_reference);
    RUN_TEST(roles_unrecognised_declaration_fails_closed_to_reference);

    /* Precedence */
    RUN_TEST(roles_precedence_ladder);

    /* A7 — the audit */
    RUN_TEST(roles_audit_reports_member_do_not_edit_contradiction);
    RUN_TEST(roles_audit_reports_member_vendored_and_upstream_contradictions);
    RUN_TEST(roles_audit_is_asymmetric_and_silent_when_consistent);

    /* Wire names */
    RUN_TEST(roles_names_round_trip);
}
