#!/bin/sh
# gen-integrations-hash.sh — emit the build-time integrity constant for
# assets/hyp-integrations.json.
#
# The binary embeds exactly ONE fact about the integration templates: the
# SHA-256 of the shipped asset file. Verifying the file against this constant
# before use preserves the tamper-evidence the templates had while they were
# compiled in — moving them out of the binary (AV-surface reduction) must not
# turn them into unauthenticated code the installer happily writes to disk.
#
# Generated, never hand-maintained: a stale constant is exactly the silent
# drift this step exists to prevent, so the header is a build product with a
# real dependency on the JSON file.
set -eu

if [ "$#" -ne 2 ]; then
    echo "usage: gen-integrations-hash.sh <asset.json> <out-header.h>" >&2
    exit 2
fi
asset="$1"
out="$2"

[ -f "$asset" ] || { echo "gen-integrations-hash: missing $asset" >&2; exit 1; }

if command -v sha256sum >/dev/null 2>&1; then
    hash=$(sha256sum "$asset" | cut -d' ' -f1)
elif command -v shasum >/dev/null 2>&1; then
    hash=$(shasum -a 256 "$asset" | cut -d' ' -f1)
else
    echo "gen-integrations-hash: neither sha256sum nor shasum available" >&2
    exit 1
fi

case "$hash" in
*[!0-9a-f]* | "")
    echo "gen-integrations-hash: bad digest '$hash'" >&2
    exit 1
    ;;
esac
if [ "${#hash}" -ne 64 ]; then
    echo "gen-integrations-hash: bad digest length for '$hash'" >&2
    exit 1
fi

mkdir -p "$(dirname "$out")"
tmp="$out.tmp.$$"
{
    echo "/* Generated by scripts/gen-integrations-hash.sh — do not edit. */"
    echo "#ifndef HYP_INTEGRATIONS_HASH_H"
    echo "#define HYP_INTEGRATIONS_HASH_H"
    echo "#define HYP_INTEGRATIONS_SHA256 \"$hash\""
    echo "#endif"
} >"$tmp"
mv "$tmp" "$out"
